name: Issue Bot Language Detection

on:
  issues:
    types: [opened]

jobs:
  detect-language-and-reply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install langdetect
        run: |
          python -m pip install --upgrade pip
          pip install langdetect

      - name: Detect issue language and comment
        id: detect_language
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/actions/detect_language_and_reply.py
