# .github/workflows/issue-reply.yml

name: Issue Response Bot with Language Detection
on:
  issues:
    types: [opened]

jobs:
  detect-and-reply:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Get issue body
        id: get_body
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueBody = context.payload.issue.body;
            return {body: issueBody};

      - name: Detect language
        id: detect_lang
        run: |
          python -m pip install --upgrade pip
          pip install langdetect
          echo "::set-output name=detected_lang::$(python -c "import langdetect; print(langdetect.detect('${{ steps.get_body.outputs.body }}'))")"

      - name: Reply to new issue (Chinese)
        if: steps.detect_lang.outputs.detected_lang == 'zh-cn'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const ISSUE_COMMENT_ZH = `
              感谢您的问题反馈！我们会在4-8小时内回复您，请耐心等待QAQ，放平心态哦~

              在等待期间，请务必查阅我们的项目文档：[生日插件快速入门](https://docs.sdjz.wiki/docs/birthday/start)。

              若确认问题是与本项目相关，请提供以下详细信息以便我们更准确地定位和解决问题：
              - 错误内容（附上完整的错误日志）
              - 截图（如有可视化错误界面）
              - 相关代码片段或仓库链接（如果方便的话）

              我们会尽快伸出援手，帮您解决遇到的难题哒！
            `;
            await context.github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: ISSUE_COMMENT_ZH
            });

      - name: Reply to new issue (English)
        if: steps.detect_lang.outputs.detected_lang == 'en'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const ISSUE_COMMENT_EN = `
              Hey there! Thanks for reaching out with your issue. We'll get back to you within 4-8 hours, so please hang tight and stay calm ~<3~

              While you're waiting, be sure to review our project documentation: [Birthday Plugin Quick Start Guide](https://docs.sdjz.wiki/docs/birthday/start).

              If the problem seems related to this project, kindly provide us with these details to help us troubleshoot more efficiently:
              - Error messages (include a full error log)
              - Screenshots (if applicable to visualize the issue)
              - Relevant code snippets or repository link (if convenient)

              Our team will assist you in tackling your issue as promptly as possible. Keep your cool – we've got this!
            `;
            await context.github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: ISSUE_COMMENT_EN
            });
